CREATE TABLE [dbo].[Card]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Name] NVARCHAR(MAX) NOT NULL, 
    [TableColumnId] UNIQUEIDENTIFIER NOT NULL, 
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(), 
    CONSTRAINT [FK_TableColumnId_TableColumn] FOREIGN KEY ([TableColumnId]) REFERENCES [TableColumn]([Id])
)
