CREATE TABLE [dbo].[Store]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Name] NVARCHAR(MAX) NOT NULL, 
    [TableId] UNIQUEIDENTIFIER NOT NULL, 
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(), 
    CONSTRAINT [FK_StoreTableId_Table] FOREIGN KEY ([TableId]) REFERENCES [Table]([Id])
)
