CREATE TABLE [dbo].[TableColumn]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Index] INT NOT NULL, 
    [Name] NVARCHAR(MAX) NOT NULL, 
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(), 
    [TableId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_TableId_Table] FOREIGN KEY ([TableId]) REFERENCES [Table]([Id])
)
