CREATE TABLE [dbo].[Table]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Name] NVARCHAR(MAX) NOT NULL, 
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(), 
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_UserId_Account] FOREIGN KEY ([UserId]) REFERENCES [Account]([Id])
)
